export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FALIURE = "REGISTER_FALIURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FALIURE = "LOGIN_FALIURE"


export const LOGIN_TWO_STEP_REQUEST = "LOGIN_TWO_STEP_RREQUEST"
export const LOGIN_TWO_STEP_RSUCCESS = "LOGIN_TWO_STEP_RSUCCESS"
export const LOGIN_TWO_STEP_RFALIURE = "LOGIN_TWO_STEP_RFALIURE"

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILURE = "SEND_VERIFICATION_OTP_FAILURE";

export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS = "ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE = "ENABLE_TWO_STEP_AUTHENTICATION_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAILURE = "SEND_RESET_PASSWORD_FAILURE";

export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST";
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS";
export const VERIFY_RESET_PASSWORD_FAILURE = "VERIFY_RESET_PASSWORD_FAILURE";


export const LOGOUT = "LOGOUT";

